root = "."
tmp_dir = "tmp"

[build]
  binary = "tmp/main"
  cmd = "go build -o tmp/main ."
  delay = 600
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  kill_delay = "0s"
  log = "air.log"
  send_interrupt = false
  stop_on_error = true