// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: encode_level

package constants
// encode_level - 日志编码级
const (
	EncodeLevelLowercasecolorlevelencoder = "LowercaseColorLevelEncoder" // LowercaseColorLevelEncoder
	EncodeLevelCapitallevelencoder = "CapitalLevelEncoder" // CapitalLevelEncoder
	EncodeLevelLowercaselevelencoder = "LowercaseLevelEncoder" // LowercaseLevelEncoder
	EncodeLevelCapitalcolorlevelencoder = "CapitalColorLevelEncoder" // CapitalColorLevelEncoder
)

// encode_levelLabelMap label mapping for encode_level
var encode_levelLabelMap = map[string]string{
	EncodeLevelLowercasecolorlevelencoder: "LowercaseColorLevelEncoder",
	EncodeLevelCapitallevelencoder: "CapitalLevelEncoder",
	EncodeLevelLowercaselevelencoder: "LowercaseLevelEncoder",
	EncodeLevelCapitalcolorlevelencoder: "CapitalColorLevelEncoder",
}

// encode_levelOptions all options for encode_level
var encode_levelOptions = []struct{
	Value string
	Label string
}{
	{ EncodeLevelLowercasecolorlevelencoder, "LowercaseColorLevelEncoder" },
	{ EncodeLevelCapitallevelencoder, "CapitalLevelEncoder" },
	{ EncodeLevelLowercaselevelencoder, "LowercaseLevelEncoder" },
	{ EncodeLevelCapitalcolorlevelencoder, "CapitalColorLevelEncoder" },
}
