// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: output_type

package constants
// output_type - 日志输出方式
const (
	OutputTypeJson = "json" // Json
	OutputTypeConsole = "console" // Console
)

// output_typeLabelMap label mapping for output_type
var output_typeLabelMap = map[string]string{
	OutputTypeJson: "Json",
	OutputTypeConsole: "Console",
}

// output_typeOptions all options for output_type
var output_typeOptions = []struct{
	Value string
	Label string
}{
	{ OutputTypeJson, "Json" },
	{ OutputTypeConsole, "Console" },
}
