// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: status

package constants
// status - 开关状态
const (
	StatusDisabled = "2" // Disabled
	StatusEnabled = "1" // Enabled
)

// statusLabelMap label mapping for status
var statusLabelMap = map[string]string{
	StatusDisabled: "Disabled",
	StatusEnabled: "Enabled",
}

// statusOptions all options for status
var statusOptions = []struct{
	Value string
	Label string
}{
	{ StatusDisabled, "Disabled" },
	{ StatusEnabled, "Enabled" },
}
