// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: task_exec

package constants
// task_exec - 计划任务执行类型
const (
	TaskExecRecurring = "recurring" // Recurring
	TaskExecOnetime = "one_time" // OneTime
)

// task_execLabelMap label mapping for task_exec
var task_execLabelMap = map[string]string{
	TaskExecRecurring: "Recurring",
	TaskExecOnetime: "OneTime",
}

// task_execOptions all options for task_exec
var task_execOptions = []struct{
	Value string
	Label string
}{
	{ TaskExecRecurring, "Recurring" },
	{ TaskExecOnetime, "OneTime" },
}
