// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: task_status

package constants
// task_status - task_status
const (
	TaskStatusError = "4" // Error
	TaskStatusDisabled = "1" // Disabled
	TaskStatusEnabled = "0" // Enabled
	TaskStatusRunning = "2" // Running
	TaskStatusCompleted = "5" // Completed
	TaskStatusPaused = "3" // Paused
)

// task_statusLabelMap label mapping for task_status
var task_statusLabelMap = map[string]string{
	TaskStatusError: "Error",
	TaskStatusDisabled: "Disabled",
	TaskStatusEnabled: "Enabled",
	TaskStatusRunning: "Running",
	TaskStatusCompleted: "Completed",
	TaskStatusPaused: "Paused",
}

// task_statusOptions all options for task_status
var task_statusOptions = []struct{
	Value string
	Label string
}{
	{ TaskStatusError, "Error" },
	{ TaskStatusDisabled, "Disabled" },
	{ TaskStatusEnabled, "Enabled" },
	{ TaskStatusRunning, "Running" },
	{ TaskStatusCompleted, "Completed" },
	{ TaskStatusPaused, "Paused" },
}
