// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/auth/access-token": {
            "get": {
                "description": "refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "refresh_token"
                ],
                "summary": "refresh token",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.AccessTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-auth_SecurityAuthenticatedUser"
                        }
                    }
                }
            }
        },
        "/v1/auth/logout": {
            "get": {
                "description": "user logout",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logout"
                ],
                "summary": "user logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-string"
                        }
                    }
                }
            }
        },
        "/v1/auth/signin": {
            "get": {
                "description": "login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "login godoc",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-auth_SecurityAuthenticatedUser"
                        }
                    }
                }
            }
        },
        "/v1/auth/signup": {
            "get": {
                "description": "register new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "register user"
                ],
                "summary": "register new user",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.CommonResponse-auth_SecurityRegisterUser"
                            }
                        }
                    }
                }
            }
        },
        "/v1/role": {
            "get": {
                "description": "get  all roles by where",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "get all roles by",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-array_role_RoleTree"
                        }
                    }
                }
            },
            "put": {
                "description": "update role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "update role",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.CommonResponseBuilder-role_ResponseRole"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role create"
                ],
                "summary": "create role",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/role.NewRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CommonResponseBuilder"
                        }
                    }
                }
            }
        },
        "/v1/role/search": {
            "get": {
                "description": "search roles by query",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search roles"
                ],
                "summary": "search roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PageList-array_role_ResponseRole"
                        }
                    }
                }
            }
        },
        "/v1/role/search-property": {
            "get": {
                "description": "search by property",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "search by property",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/role/tree": {
            "get": {
                "description": "get tree roles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tree roles"
                ],
                "summary": "get tree roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-role_RoleNode"
                        }
                    }
                }
            }
        },
        "/v1/role/{id}": {
            "get": {
                "description": "get roles by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "roles"
                ],
                "summary": "get roles",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/role.ResponseRole"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete role by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "role"
                ],
                "summary": "delete role",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-int"
                        }
                    }
                }
            }
        },
        "/v1/upload/single": {
            "post": {
                "description": "upload single file get file info",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "single file upload",
                "parameters": [
                    {
                        "type": "file",
                        "description": "fileResource",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-github_com_gbrayhan_microservices-go_src_domain_sys_files_SysFiles"
                        }
                    }
                }
            }
        },
        "/v1/user": {
            "get": {
                "description": "get  all users by where",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get all users by",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-array_user_ResponseUser"
                        }
                    }
                }
            },
            "put": {
                "description": "update userinfo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "userinfo"
                ],
                "summary": "update userinfo",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.CommonResponseBuilder-user_ResponseUser"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user create"
                ],
                "summary": "create user",
                "parameters": [
                    {
                        "description": "JSON Data",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.NewUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.CommonResponseBuilder"
                        }
                    }
                }
            }
        },
        "/v1/user/search": {
            "get": {
                "description": "search users by query",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search users"
                ],
                "summary": "search users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "PageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sortBy",
                        "name": "sortBy",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "sortDirection",
                        "name": "sortDirection",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "status",
                        "name": "status_match",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "userName",
                        "name": "user_name_like",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.PageList-array_user_ResponseUser"
                        }
                    }
                }
            }
        },
        "/v1/user/search-property": {
            "get": {
                "description": "search by property",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "search by property",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/v1/user/{id}": {
            "get": {
                "description": "get users by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "get users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.ResponseUser"
                        }
                    }
                }
            },
            "delete": {
                "description": "delete user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "delete user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CommonResponse-int"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.AccessTokenRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "auth.DataSecurityAuthenticated": {
            "type": "object",
            "properties": {
                "expirationAccessDateTime": {
                    "type": "string"
                },
                "expirationRefreshDateTime": {
                    "type": "string"
                },
                "jwtAccessToken": {
                    "type": "string"
                },
                "jwtRefreshToken": {
                    "type": "string"
                }
            }
        },
        "auth.DataUserAuthenticated": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "header_img": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "user_name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "user_name"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "user_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "auth.SecurityAuthenticatedUser": {
            "type": "object",
            "properties": {
                "security": {
                    "$ref": "#/definitions/auth.DataSecurityAuthenticated"
                },
                "userinfo": {
                    "$ref": "#/definitions/auth.DataUserAuthenticated"
                }
            }
        },
        "auth.SecurityRegisterUser": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.DataUserAuthenticated"
                }
            }
        },
        "controllers.CommonResponseBuilder": {
            "type": "object"
        },
        "controllers.CommonResponseBuilder-role_ResponseRole": {
            "type": "object"
        },
        "controllers.CommonResponseBuilder-user_ResponseUser": {
            "type": "object"
        },
        "domain.CommonResponse-array_role_RoleTree": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.RoleTree"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-array_user_ResponseUser": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.ResponseUser"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-auth_SecurityAuthenticatedUser": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.SecurityAuthenticatedUser"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-auth_SecurityRegisterUser": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/auth.SecurityRegisterUser"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-github_com_gbrayhan_microservices-go_src_domain_sys_files_SysFiles": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/github_com_gbrayhan_microservices-go_src_domain_sys_files.SysFiles"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-int": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-role_RoleNode": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/role.RoleNode"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CommonResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "domain.CustomTime": {
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        },
        "domain.DataFilters": {
            "type": "object",
            "properties": {
                "dataRanges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.DateRangeFilter"
                    }
                },
                "likeFilters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "matches": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "sortBy": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sortDirection": {
                    "$ref": "#/definitions/domain.SortDirection"
                }
            }
        },
        "domain.DateRangeFilter": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "domain.PageList-array_role_ResponseRole": {
            "type": "object",
            "properties": {
                "filters": {
                    "$ref": "#/definitions/domain.DataFilters"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.ResponseRole"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "domain.PageList-array_user_ResponseUser": {
            "type": "object",
            "properties": {
                "filters": {
                    "$ref": "#/definitions/domain.DataFilters"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/user.ResponseUser"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_page": {
                    "type": "integer"
                }
            }
        },
        "domain.SortDirection": {
            "type": "string",
            "enum": [
                "asc",
                "desc"
            ],
            "x-enum-varnames": [
                "SortAsc",
                "SortDesc"
            ]
        },
        "github_com_gbrayhan_microservices-go_src_domain_sys_files.SysFiles": {
            "type": "object",
            "properties": {
                "file_md5": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "role.NewRoleRequest": {
            "type": "object",
            "required": [
                "name",
                "parent_id"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "role.ResponseRole": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/domain.CustomTime"
                },
                "default_router": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "boolean"
                },
                "updated_at": {
                    "$ref": "#/definitions/domain.CustomTime"
                }
            }
        },
        "role.RoleNode": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.RoleNode"
                    }
                },
                "key": {
                    "type": "string"
                },
                "path": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "role.RoleTree": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/role.RoleTree"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "default_router": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "parent_id": {
                    "type": "integer"
                },
                "path": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "status": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "user.NewUserRequest": {
            "type": "object",
            "required": [
                "email",
                "user_name"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "header_img": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "user.ResponseUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "$ref": "#/definitions/domain.CustomTime"
                },
                "email": {
                    "type": "string"
                },
                "header_img": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "updated_at": {
                    "$ref": "#/definitions/domain.CustomTime"
                },
                "user_name": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
