// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: file_storage_engine

package constants
// file_storage_engine - storage_engine
const (
	FileStorageEngineAliyunoss = "aliyunoss" // Aliyunoss
	FileStorageEngineLocal = "local" // Local
)

// file_storage_engineLabelMap label mapping for file_storage_engine
var file_storage_engineLabelMap = map[string]string{
	FileStorageEngineAliyunoss: "Aliyunoss",
	FileStorageEngineLocal: "Local",
}

// file_storage_engineOptions all options for file_storage_engine
var file_storage_engineOptions = []struct{
	Value string
	Label string
}{
	{ FileStorageEngineAliyunoss, "Aliyunoss" },
	{ FileStorageEngineLocal, "Local" },
}
