// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: api_group

package constants
// api_group - Api分组
const (
	ApiGroupOperation = "operation" // Operation
	ApiGroupApi = "api" // Api
	ApiGroupMenu = "menu" // Menu
	ApiGroupUser = "user" // User
	ApiGroupFile = "file" // File
	ApiGroupRole = "role" // Role
	ApiGroupDictionary = "dictionary" // Dictionary
	ApiGroupSchedule = "schedule" // Schedule
	ApiGroupSystem = "system" // System
	ApiGroupAuth = "auth" // Auth
	ApiGroupOther = "other" // Other
)

// api_groupLabelMap label mapping for api_group
var api_groupLabelMap = map[string]string{
	ApiGroupOperation: "Operation",
	ApiGroupApi: "Api",
	ApiGroupMenu: "Menu",
	ApiGroupUser: "User",
	ApiGroupFile: "File",
	ApiGroupRole: "Role",
	ApiGroupDictionary: "Dictionary",
	ApiGroupSchedule: "Schedule",
	ApiGroupSystem: "System",
	ApiGroupAuth: "Auth",
	ApiGroupOther: "Other",
}

// api_groupOptions all options for api_group
var api_groupOptions = []struct{
	Value string
	Label string
}{
	{ ApiGroupOperation, "Operation" },
	{ ApiGroupApi, "Api" },
	{ ApiGroupMenu, "Menu" },
	{ ApiGroupUser, "User" },
	{ ApiGroupFile, "File" },
	{ ApiGroupRole, "Role" },
	{ ApiGroupDictionary, "Dictionary" },
	{ ApiGroupSchedule, "Schedule" },
	{ ApiGroupSystem, "System" },
	{ ApiGroupAuth, "Auth" },
	{ ApiGroupOther, "Other" },
}
