// Code generated by go generate; DO NOT EDIT.
// Generated at: 2025-10-20 15:54:20
// Dictionary type: api_method

package constants
// api_method - api_method
const (
	ApiMethodPatch = "PATCH" // PATCH
	ApiMethodHead = "HEAD" // HEAD
	ApiMethodTrace = "TRACE" // TRACE
	ApiMethodGet = "GET" // GET
	ApiMethodOptions = "OPTIONS" // OPTIONS
	ApiMethodPut = "PUT" // PUT
	ApiMethodDelete = "DELETE" // DELETE
	ApiMethodPost = "POST" // POST
)

// api_methodLabelMap label mapping for api_method
var api_methodLabelMap = map[string]string{
	ApiMethodPatch: "PATCH",
	ApiMethodHead: "HEAD",
	ApiMethodTrace: "TRACE",
	ApiMethodGet: "GET",
	ApiMethodOptions: "OPTIONS",
	ApiMethodPut: "PUT",
	ApiMethodDelete: "DELETE",
	ApiMethodPost: "POST",
}

// api_methodOptions all options for api_method
var api_methodOptions = []struct{
	Value string
	Label string
}{
	{ ApiMethodPatch, "PATCH" },
	{ ApiMethodHead, "HEAD" },
	{ ApiMethodTrace, "TRACE" },
	{ ApiMethodGet, "GET" },
	{ ApiMethodOptions, "OPTIONS" },
	{ ApiMethodPut, "PUT" },
	{ ApiMethodDelete, "DELETE" },
	{ ApiMethodPost, "POST" },
}
